Build: Symbol Server: Downgraded failure to add source indexing to a pdb from a breaking exception to a log message (Windows-based platforms).
PdbStr.exe tool that is used to add source information to .pdb can't handle large (> 4 BG) symbol files and there isn't much we can do about it. Some of our builds produce such symbols which leads to whole build tasks being failed (and symbols not being stored at all).

I tried to predice such cases by checking the size of .pdb before trying to invoke PdbStr.exe and it works in some cases, but apparently it's not precise enough because we have cases in our build farm which pass my check but fail later on when PdbStr.exe is started.

#preflight 63756b4832484253059d8856
#rb none
#rnx

[CL 23165019 by wojciech krywult in ue5-release-engine-staging branch]