SwitchboardListener: Fix for building with bForceEnableExceptions (error C2712: cannot use __try in functions that require object unwinding).
#jira UE-145172
#rb matt.johnson
#preflight 6244bb9ff4217035fa806ae9

#ROBOMERGE-AUTHOR: zach.brockway
#ROBOMERGE-SOURCE: CL 19564149 in //UE5/Main/...
#ROBOMERGE-BOT: UE5 (Main -> Release-Engine-Staging) (v937-19513599)

[CL 19564173 by zach brockway in ue5-release-engine-staging branch]